spring:
  config:
    import: optional:file:/config.properties #추가 설정 파일 로드
  application:
    name: lostArkProject
  datasource:
    url: jdbc:mysql://localhost:3306/LOSTARKPROJECT?serverTimeZone=Asia/Seoul&allowMultiQueries=true
    username: root
    password: 1234
    driverClassName: com.mysql.cj.jdbc.Driver
  mail:
    host: smtp.gmail.com
    port: 587
    username: ysh0621000@gmail.com
    password: {emailPassword}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
    auth-code-expiration-millis: 600000  # 10 * 60 * 1000 == 10분
  web:
    resources:
      static-locations: classpath:/static/
  thymeleaf:
    cache: false

mybatis:
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: com.teamProject.lostArkProject
  configuration:
    map-underscore-to-camel-case: true

server:
  port: 80