spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: ysh0621000@gmail.com
    password: wipf eitu qsir ompf
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
    auth-code-expiration-millis: 600000  # 10 * 60 * 1000 == 10분